# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'Anetos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Anetos
  pod ‘SDWebImage’
  pod "SwiftyJSON", ">= 2.2"
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'

  target 'AnetosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AnetosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
